# Generated by Django 4.2.11 on 2024-03-11 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LibraryManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Borrower_Student',
            new_name='Student_Information',
        ),
    ]
