# Generated by Django 4.2.11 on 2024-03-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0002_rename_book_borrower_student_student_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_information',
            options={'verbose_name': 'Student_Information', 'verbose_name_plural': 'Student_Information'},
        ),
    ]
