# Generated by Django 4.2.11 on 2024-03-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0002_librarycard_book_borrower_student_alter_loan_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='member',
            new_name='book_borrower_student',
        ),
        migrations.RemoveField(
            model_name='book_borrower_student',
            name='email',
        ),
    ]
