# Generated by Django 4.2.11 on 2024-03-13 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0005_alter_author_created_at_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='loan_date',
            new_name='borrow_date',
        ),
        migrations.AddField(
            model_name='borrower',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
