# Generated by Django 4.2.11 on 2024-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0006_rename_loan_date_borrower_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
