# Generated by Django 4.2.11 on 2024-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0010_student_information_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_information',
            name='Penalty',
            field=models.CharField(default='No Penalty', max_length=15),
        ),
    ]
