# Generated by Django 4.2.11 on 2024-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0012_student_information_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='book',
        ),
        migrations.AddField(
            model_name='borrower',
            name='books',
            field=models.ManyToManyField(to='LibraryManagementSystem.book'),
        ),
    ]
