# Generated by Django 4.2.11 on 2024-03-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0014_remove_student_information_branch_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branch'},
        ),
    ]
