# Generated by Django 4.2.11 on 2024-03-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0015_alter_branch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystem.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_information',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystem.branch'),
            preserve_default=False,
        ),
    ]
