# Generated by Django 4.2.11 on 2024-03-24 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LibraryManagementSystem', '0016_borrower_branch_student_information_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='book_borrower_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
