# Generated by Django 4.2.11 on 2024-03-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0017_alter_borrower_book_borrower_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_information',
            name='user',
        ),
    ]
