# Generated by Django 4.2.11 on 2024-03-29 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0018_remove_student_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycard',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='librarycard',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
