# Generated by Django 4.2.11 on 2024-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=50)),
                ('website_name', models.CharField(max_length=50)),
                ('customer_message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact_us',
                'verbose_name_plural': 'Contact_us',
            },
        ),
    ]
