# Generated by Django 4.2.11 on 2024-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Staff'), (4, 'NormalUser')], null=True),
        ),
    ]
