# Generated by Django 4.2.11 on 2024-03-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_myuser_is_superuser_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': [('view_only', 'Can view but not change anything')]},
        ),
    ]
