# Generated by Django 4.2.11 on 2024-03-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
    ]
